<html>
<head>
	<title>Acceptation pour la création du site ###SITE_NAME###</title>
</head>
<body>
	<p>
		<a name="french"></a>
		Bonjour ,<br />
		<br />
		La demande pour la création du site ###SITE_NAME### vient d'être validée par l'administrateur du site.<br />
		Vous pouvez administrer le site à partir de l'adresse suivante : ###URL_SITE###<br />


		<br />
		Cordialement,<br />
		L'administrateur du site
	</p>
</body>
</html>