<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2011-08-17 10:17

$extensionPath = t3lib_extMgm::extPath('ics_utopia');
$extensionClassesPath = t3lib_extMgm::extPath('ics_utopia') . 'Classes/';
return array(
	'tx_icsutopia_templates_pagepostaction' => $extensionClassesPath . 'Templates/class.tx_icsutopia_templates_pagepostaction.php',
	'tx_icsutopia_module1' => $extensionPath . 'mod1/index.php',
	'tx_icsutopia_module2' => $extensionPath . 'mod2/index.php',
	'tx_icsutopia_module3' => $extensionPath . 'mod3/index.php',
	'tx_icsutopia_module4' => $extensionPath . 'mod4/index.php',
	'tx_icsutopia_module5' => $extensionPath . 'mod5/index.php',
	'tx_icsutopia_pi1' => $extensionPath . 'pi1/class.tx_icsutopia_pi1.php',
);
?>